import { shotFrom } from "../test/projectFixtures";
import { migrateScene } from "@oculo/scene-schema";
// @vitest-environment jsdom
import { act, cleanup, fireEvent, render, screen, waitFor, within } from "@testing-library/react";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import userEvent from "@testing-library/user-event";
import { ShotSheetWorkspace } from "./ShotSheetWorkspace";
import { DEFAULT_CAMERA, type SceneWorkspace } from "../types/project";
import type { WorkspaceStore } from "../store/WorkspaceStore";
import type { PreparedShare } from "../services/SharingService";
import { ShotSheetError, type GeneratedSheetPage, type SheetDocument } from "../services/shotSheet";
import type * as ShotSheetModule from "../services/shotSheet";

const mocks = vi.hoisted(() => ({
  generate: vi.fn(),
  prepare: vi.fn(),
  url: vi.fn(),
  revoke: vi.fn(),
}));
vi.mock("../services/SharingService", () => ({
  createSharingService: () => ({ prepare: mocks.prepare }),
}));
vi.mock("../services/shotSheet", async (importOriginal) => ({
  ...(await importOriginal<typeof ShotSheetModule>()),
  generateShotSheet: mocks.generate,
}));

function deferred<T>() {
  let resolve!: (value: T) => void;
  let reject!: (reason: unknown) => void;
  const promise = new Promise<T>((yes, no) => {
    resolve = yes;
    reject = no;
  });
  return { promise, resolve, reject };
}

function projectFixture(): SceneWorkspace {
  return {
    sceneId: "station",
    assetVersionId: "legacy-scene:station",
    projectSceneId: "scene-1",
    projectSceneName: "Scene",
    id: "film",
    name: "Station",
    updatedAt: 1,
    scene: migrateScene({
      id: "station",
      name: "Station scene",
      splatUrl: "https://example.com/a.spz",
      source: "bundled",
    }),
    camera: { ...structuredClone(DEFAULT_CAMERA), focalLengthMm: 120 },
    shots: ["Wide", "Close"].map((name, index) =>
      shotFrom({
        assetVersionId: "legacy-scene:station",
        id: `s${index + 1}`,
        name,
        sceneId: "station",
        camera: structuredClone(DEFAULT_CAMERA),
        notes: "",
        createdAt: new Date(0).toISOString(),
        thumbnailDataUrl: "data:image/png;base64,saved",
      }),
    ),
    settings: { showGrid: true, showSafeFrame: true, reduceMotion: false },
  };
}

function page(name = "sheet.png"): GeneratedSheetPage {
  return {
    name,
    mimeType: "image/png",
    blob: new Blob(["exact generated bytes"], { type: "image/png" }),
    width: 1440,
    height: 2036,
    text: `Text printed on ${name}`,
  };
}

function delivery(): PreparedShare {
  return {
    files: [],
    canShare: true,
    canDownload: true,
    share: vi.fn().mockResolvedValue("shared"),
    download: vi.fn(),
    dispose: vi.fn(),
  };
}

function setup(
  project = projectFixture(),
  put = vi.fn<(project: SceneWorkspace) => Promise<void>>().mockResolvedValue(undefined),
) {
  const store: WorkspaceStore = { put };
  const onClose = vi.fn();
  const onRecapture = vi.fn();
  const onChange = vi.fn();
  const view = render(
    <ShotSheetWorkspace
      initialProject={project}
      store={store}
      onClose={onClose}
      onRecapture={onRecapture}
      onChange={onChange}
    />,
  );
  return { ...view, store, put, onClose, onRecapture, onChange };
}

beforeEach(() => {
  mocks.generate.mockReset().mockResolvedValue([page()]);
  mocks.prepare.mockReset().mockResolvedValue(delivery());
  mocks.url.mockReset().mockReturnValue("blob:exact-page");
  mocks.revoke.mockReset();
  vi.stubGlobal(
    "URL",
    class extends URL {
      static createObjectURL = mocks.url;
      static revokeObjectURL = mocks.revoke;
    },
  );
});
afterEach(() => {
  cleanup();
  vi.unstubAllGlobals();
});

describe("keyboard viewport and field visibility", () => {
  function viewportFixture() {
    const viewport = Object.assign(new EventTarget(), { height: 900, offsetTop: 0, scale: 1 });
    const frames = new Map<number, FrameRequestCallback>();
    let nextFrame = 0;
    const request = vi.fn((callback: FrameRequestCallback) => {
      frames.set(++nextFrame, callback);
      return nextFrame;
    });
    const cancel = vi.fn((id: number) => frames.delete(id));
    vi.stubGlobal("visualViewport", viewport);
    vi.stubGlobal("requestAnimationFrame", request);
    vi.stubGlobal("cancelAnimationFrame", cancel);
    const flush = () =>
      act(() => {
        const pending = [...frames.values()];
        frames.clear();
        pending.forEach((callback) => callback(0));
      });
    return { viewport, frames, request, cancel, flush };
  }

  function rect(top: number, bottom: number): DOMRect {
    return { top, bottom, height: bottom - top, left: 0, right: 400, width: 400 } as DOMRect;
  }

  it("keeps a lower focused field visible inside the list through keyboard pan, resize and dismissal", async () => {
    const { viewport, request, flush } = viewportFixture();
    const view = setup();
    const workspace = screen.getByRole("main");
    const body = view.container.querySelector<HTMLDivElement>(".sheet-body")!;
    const field = screen.getByLabelText("Title for Wide") as HTMLInputElement;
    vi.spyOn(body, "getBoundingClientRect").mockImplementation(() =>
      rect(140, viewport.height === 900 ? 800 : 500),
    );
    vi.spyOn(field, "getBoundingClientRect").mockImplementation(() =>
      rect(520 - body.scrollTop, 564 - body.scrollTop),
    );
    act(() => field.focus());
    viewport.height = 600;
    viewport.offsetTop = 64;
    viewport.dispatchEvent(new Event("resize"));
    viewport.dispatchEvent(new Event("scroll"));
    expect(request).toHaveBeenCalledTimes(1);
    flush();
    expect(workspace.style.top).toBe("64px");
    expect(workspace.style.height).toBe("600px");
    expect(body.scrollTop).toBe(76);
    expect(document.activeElement).toBe(field);
    expect(field.getBoundingClientRect().bottom).toBe(488);

    fireEvent.change(field, { target: { value: "Garden overview" } });
    act(() => field.blur());
    viewport.height = 900;
    viewport.offsetTop = 0;
    viewport.dispatchEvent(new Event("resize"));
    flush();
    expect(workspace.style.top).toBe("0px");
    expect(workspace.style.height).toBe("900px");
    expect(body.scrollTop).toBe(76);
    fireEvent.click(screen.getByRole("button", { name: "Close shot sheet" }));
    await waitFor(() => expect(view.onClose).toHaveBeenCalledTimes(1));
    expect(view.put.mock.calls.at(-1)![0].shots[0]!.name).toBe("Garden overview");
  });

  it("reveals a newly focused field above the list and leaves a tall textarea stable", () => {
    const { flush } = viewportFixture();
    const view = setup();
    const body = view.container.querySelector<HTMLDivElement>(".sheet-body")!;
    const field = screen.getByLabelText("Notes for Wide");
    body.scrollTop = 200;
    vi.spyOn(body, "getBoundingClientRect").mockReturnValue(rect(140, 500));
    const bounds = vi
      .spyOn(field, "getBoundingClientRect")
      .mockImplementation(() => rect(320 - body.scrollTop, 420 - body.scrollTop));
    act(() => field.focus());
    flush();
    expect(body.scrollTop).toBe(168);
    expect(field.getBoundingClientRect().top).toBe(152);
    bounds.mockReturnValue(rect(100, 650));
    fireEvent.focusIn(field);
    flush();
    expect(body.scrollTop).toBe(168);
  });

  it("preserves user scrolling away from a focused field during viewport pan and keyboard dismissal", () => {
    const { viewport, flush } = viewportFixture();
    const view = setup();
    const workspace = screen.getByRole("main");
    const body = view.container.querySelector<HTMLDivElement>(".sheet-body")!;
    const field = screen.getByLabelText("Title for Wide");
    vi.spyOn(body, "getBoundingClientRect").mockReturnValue(rect(140, 500));
    const bounds = vi.spyOn(field, "getBoundingClientRect").mockReturnValue(rect(200, 244));
    act(() => field.focus());
    viewport.height = 600;
    viewport.dispatchEvent(new Event("resize"));
    flush();
    body.scrollTop = 300;
    bounds.mockReturnValue(rect(-100, -56));
    viewport.offsetTop = 64;
    viewport.dispatchEvent(new Event("scroll"));
    flush();
    expect(workspace.style.top).toBe("64px");
    expect(body.scrollTop).toBe(300);
    viewport.height = 900;
    viewport.offsetTop = 0;
    viewport.dispatchEvent(new Event("resize"));
    flush();
    expect(workspace.style.height).toBe("900px");
    expect(workspace.style.top).toBe("0px");
    expect(body.scrollTop).toBe(300);
    expect(document.activeElement).toBe(field);
  });

  it("does not compensate pinch zoom and removes viewport listeners and queued work on unmount", () => {
    const { viewport, request, cancel, frames, flush } = viewportFixture();
    const view = setup();
    const workspace = screen.getByRole("main");
    viewport.scale = 2;
    viewport.height = 450;
    viewport.offsetTop = 120;
    viewport.dispatchEvent(new Event("resize"));
    flush();
    expect(workspace.style.height).toBe("900px");
    expect(workspace.style.top).toBe("0px");
    viewport.scale = 1;
    viewport.height = 650;
    viewport.offsetTop = 64;
    window.dispatchEvent(new Event("resize"));
    flush();
    expect(workspace.style.height).toBe("650px");
    expect(workspace.style.top).toBe("64px");
    viewport.dispatchEvent(new Event("scroll"));
    expect(frames.size).toBe(1);
    view.unmount();
    expect(cancel).toHaveBeenCalledTimes(1);
    expect(frames.size).toBe(0);
    const before = request.mock.calls.length;
    viewport.dispatchEvent(new Event("resize"));
    viewport.dispatchEvent(new Event("scroll"));
    window.dispatchEvent(new Event("resize"));
    workspace.dispatchEvent(new Event("focusin"));
    expect(request).toHaveBeenCalledTimes(before);
  });
});

describe("shot sheet edits and durable navigation", () => {
  it("guards every edit while close waits and hands off the latest saved snapshot once", async () => {
    const write = deferred<void>();
    const put = vi.fn<(project: SceneWorkspace) => Promise<void>>().mockReturnValue(write.promise);
    const view = setup(projectFixture(), put);
    fireEvent.change(screen.getByLabelText("Project title"), { target: { value: "Latest title" } });
    fireEvent.change(screen.getByLabelText("Notes for Wide"), {
      target: { value: "Latest notes" },
    });
    fireEvent.click(screen.getByRole("button", { name: "Close shot sheet" }));
    expect(view.onClose).not.toHaveBeenCalled();
    expect((screen.getByLabelText("Notes for Wide") as HTMLTextAreaElement).disabled).toBe(true);
    expect((screen.getByLabelText("Title for Wide") as HTMLInputElement).disabled).toBe(true);
    expect(
      (screen.getByRole("button", { name: "Include all" }) as HTMLButtonElement).disabled,
    ).toBe(true);
    fireEvent.change(screen.getByLabelText("Notes for Wide"), { target: { value: "Too late" } });
    fireEvent.click(screen.getByRole("button", { name: "Close shot sheet" }));
    await act(async () => write.resolve());
    expect(view.onClose).toHaveBeenCalledTimes(1);
    const saved = view.onClose.mock.calls[0]![0] as SceneWorkspace;
    expect(saved.name).toBe("Latest title");
    expect(saved.shots[0]!.notes).toBe("Latest notes");
    expect(put.mock.calls.at(-1)![0]).toEqual(saved);
  });

  it("stays editable after a failed save and opens the scene only after edits are committed", async () => {
    const project = projectFixture();
    delete project.shots[0]!.thumbnailDataUrl;
    const put = vi
      .fn<(project: SceneWorkspace) => Promise<void>>()
      .mockRejectedValueOnce(new Error("Storage full"))
      .mockResolvedValue(undefined);
    const view = setup(project, put);
    fireEvent.change(screen.getByLabelText("Notes for Wide"), {
      target: { value: "Preserve this" },
    });
    fireEvent.click(screen.getByRole("button", { name: "Open in scene" }));
    await screen.findByText("Storage full");
    expect(view.onRecapture).not.toHaveBeenCalled();
    expect((screen.getByLabelText("Notes for Wide") as HTMLTextAreaElement).disabled).toBe(false);
    fireEvent.click(screen.getByRole("button", { name: "Retry save" }));
    await waitFor(() => expect(screen.getByText("Saved on device")).toBeTruthy());
    fireEvent.click(screen.getByRole("button", { name: "Open in scene" }));
    await waitFor(() => expect(view.onRecapture).toHaveBeenCalledTimes(1));
    expect(view.onRecapture.mock.calls[0]![0].shots[0].notes).toBe("Preserve this");
    expect(view.onRecapture.mock.calls[0]![1]).toBe("s1");
  });

  it("shows the generated sequence independently of editable names and excluded rows", async () => {
    setup();
    fireEvent.click(screen.getByRole("checkbox", { name: "Include Wide" }));
    expect(screen.getByText("Excluded from sheet")).toBeTruthy();
    const closeRow = screen.getByRole("checkbox", { name: "Include Close" }).closest("li")!;
    expect(within(closeRow).getByText("Shot 01 on sheet")).toBeTruthy();
    fireEvent.click(screen.getByRole("button", { name: "Move Close earlier" }));
    fireEvent.click(screen.getByRole("button", { name: "Preview shot sheet" }));
    await screen.findByRole("button", { name: "Share shot sheet" });
    const document = mocks.generate.mock.calls[0]![0] as SheetDocument;
    expect(document.shots.map(({ id, number }) => [id, number])).toEqual([["s2", 1]]);
    expect(document.shots[0]!.camera.focalLengthMm).toBe(35);
  });
});

describe("generated preview and delivery lifecycle", () => {
  it("reads only the current generated page text in selected order and clears it when the sheet changes", async () => {
    const project = projectFixture();
    project.scene.attribution = { text: "Location by filmmaker", license: "CC BY 4.0" };
    project.shotSheet = { version: 1, excludedShotIds: ["s1"] };
    project.shots[0]!.notes = "An excluded note must not appear.";
    project.shots[1]!.notes = "東京 café 👩🏽‍💻 حافظ على الباب\n".repeat(120) + "END OF FULL NOTES";
    project.shots[1] = shotFrom({
      ...project.shots[1]!,
      camera: {
        ...structuredClone(DEFAULT_CAMERA),
        focalLengthMm: 85,
        sensorWidthMm: 24,
        sensorHeightMm: 18,
        output: { aspectRatio: 4 / 3, crop: "center-inside-sensor" as const },
      },
    });
    let rendered: GeneratedSheetPage[] = [];
    mocks.generate.mockImplementation(async (snapshot: SheetDocument) => {
      const selected = snapshot.shots[0]!;
      const split = Math.floor(selected.notes.length / 2);
      const header = `${snapshot.title}\nLocation: ${snapshot.location}\nGenerated ${snapshot.generatedAt.slice(0, 10)} (UTC)\n${snapshot.attribution}`;
      rendered = [
        {
          ...page("first.png"),
          text: `${header}\nSHOT 01 / ${selected.name}\n${selected.metadata}\n${selected.notes.slice(0, split)}`,
        },
        {
          ...page("second.png"),
          text: `${header}\nSHOT 01 / CONTINUED\n${selected.notes.slice(split)}\nPage 2 / 2`,
        },
      ];
      return rendered;
    });
    const user = userEvent.setup();
    setup(project);
    await user.click(screen.getByRole("button", { name: "Preview shot sheet" }));
    await screen.findByRole("button", { name: "Share all pages" });
    const snapshot = mocks.generate.mock.calls[0]![0] as SheetDocument;
    expect(snapshot.shots.map(({ id, number }) => [id, number])).toEqual([["s2", 1]]);
    const firstSummary = screen.getByText("Read text for page 1");
    expect(firstSummary.closest("details")?.open).toBe(false);
    await user.click(firstSummary);
    const firstText = screen.getByRole("region", { name: "Text for shot sheet page 1" });
    expect(firstText.textContent).toBe(rendered[0]!.text);
    expect(firstText.textContent).toContain("SHOT 01 / Close");
    expect(firstText.textContent).toContain("85mm prime · Sensor 24 × 18 mm · 4:3");
    expect(firstText.textContent).toContain("Location by filmmaker · CC BY 4.0");
    expect(firstText.textContent).not.toContain("excluded note");
    const originalImage = screen.getByRole("img", { name: "Shot sheet page 1 of 2 for Station" });
    expect(originalImage.getAttribute("alt")?.length).toBeLessThan(100);
    await user.click(screen.getByRole("button", { name: "Enlarge (100%)" }));
    expect(screen.getByRole("img", { name: "Shot sheet page 1 of 2 for Station" })).toBe(
      originalImage,
    );
    expect(firstText.textContent).toBe(rendered[0]!.text);
    await user.click(screen.getByRole("button", { name: "Next page" }));
    expect(screen.queryByRole("region", { name: "Text for shot sheet page 1" })).toBeNull();
    const secondSummary = screen.getByText("Read text for page 2");
    expect(secondSummary.closest("details")?.open).toBe(false);
    await user.click(secondSummary);
    const secondText = screen.getByRole("region", { name: "Text for shot sheet page 2" });
    expect(secondText.textContent).toBe(rendered[1]!.text);
    expect(secondText.textContent).toContain("SHOT 01 / CONTINUED");
    expect(secondText.textContent).toContain("END OF FULL NOTES");
    expect(mocks.generate).toHaveBeenCalledTimes(1);
    expect(mocks.url).toHaveBeenCalledTimes(2);
    await user.click(screen.getByRole("button", { name: "Edit sheet" }));
    expect(screen.queryByText(/Read text for page/)).toBeNull();
    expect(screen.queryByText("END OF FULL NOTES")).toBeNull();
    fireEvent.change(screen.getByLabelText("Notes for Close"), {
      target: { value: "Revised note" },
    });
    await user.click(screen.getByRole("button", { name: "Preview shot sheet" }));
    await screen.findByRole("button", { name: "Share all pages" });
    await user.click(screen.getByText("Read text for page 1"));
    expect(screen.getByRole("region", { name: "Text for shot sheet page 1" }).textContent).toBe(
      rendered[0]!.text,
    );
    expect(mocks.generate).toHaveBeenCalledTimes(2);
    expect((mocks.generate.mock.calls[1]![0] as SheetDocument).shots[0]!.notes).toBe(
      "Revised note",
    );
  });

  it("enlarges the same page image without regenerating and resets the view when changing pages", async () => {
    const first = page("first.png");
    const second = page("second.png");
    mocks.generate.mockResolvedValue([first, second]);
    mocks.url.mockReturnValueOnce("blob:first-page").mockReturnValueOnce("blob:second-page");
    setup();
    fireEvent.click(screen.getByRole("button", { name: "Preview shot sheet" }));
    await screen.findByRole("button", { name: "Share all pages" });
    const originalImage = await screen.findByRole("img", {
      name: "Shot sheet page 1 of 2 for Station",
    });
    const viewport = screen.getByRole("region", { name: "Page 1 image preview" });
    expect(viewport.tabIndex).toBe(0);
    expect(screen.getByRole("button", { name: "Fit page" }).getAttribute("aria-pressed")).toBe(
      "true",
    );

    fireEvent.click(screen.getByRole("button", { name: "Enlarge (100%)" }));
    const enlarged = screen.getByRole("img", { name: "Shot sheet page 1 of 2 for Station" });
    expect(enlarged).toBe(originalImage);
    expect(enlarged.getAttribute("src")).toBe("blob:first-page");
    expect(enlarged.style.width).toBe("1440px");
    expect(enlarged.style.height).toBe("2036px");
    expect(
      screen.getByRole("button", { name: "Enlarge (100%)" }).getAttribute("aria-pressed"),
    ).toBe("true");
    viewport.scrollLeft = 200;
    viewport.scrollTop = 400;
    fireEvent.click(screen.getByRole("button", { name: "Fit page" }));
    expect([viewport.scrollLeft, viewport.scrollTop]).toEqual([0, 0]);
    expect(originalImage.style.width).toBe("");
    fireEvent.click(screen.getByRole("button", { name: "Enlarge (100%)" }));
    viewport.scrollLeft = 300;
    viewport.scrollTop = 500;
    expect(mocks.url).toHaveBeenCalledTimes(1);
    expect(mocks.revoke).not.toHaveBeenCalled();

    fireEvent.click(screen.getByRole("button", { name: "Next page" }));
    const nextImage = await screen.findByRole("img", {
      name: "Shot sheet page 2 of 2 for Station",
    });
    expect(nextImage.getAttribute("src")).toBe("blob:second-page");
    expect(nextImage.style.width).toBe("");
    expect(screen.getByRole("button", { name: "Fit page" }).getAttribute("aria-pressed")).toBe(
      "true",
    );
    expect([viewport.scrollLeft, viewport.scrollTop]).toEqual([0, 0]);
    expect(screen.getAllByRole("img")).toHaveLength(1);
    expect(mocks.url).toHaveBeenNthCalledWith(1, first.blob);
    expect(mocks.url).toHaveBeenNthCalledWith(2, second.blob);
    expect(mocks.revoke).toHaveBeenCalledWith("blob:first-page");
    expect(mocks.generate).toHaveBeenCalledTimes(1);
    expect(mocks.prepare).toHaveBeenCalledTimes(1);
  });

  it("preserves exact pages after preparation failure and retries delivery without regenerating", async () => {
    const artifact = page();
    const prepared = delivery();
    mocks.generate.mockResolvedValue([artifact]);
    mocks.prepare.mockRejectedValueOnce(new Error("Low storage")).mockResolvedValue(prepared);
    setup();
    fireEvent.click(screen.getByRole("button", { name: "Preview shot sheet" }));
    await screen.findByText("Low storage");
    expect(
      await screen.findByRole("img", { name: "Shot sheet page 1 of 1 for Station" }),
    ).toBeTruthy();
    expect(mocks.url).toHaveBeenCalledWith(artifact.blob);
    fireEvent.click(screen.getByText("Read text for page 1"));
    expect(screen.getByRole("region", { name: "Text for shot sheet page 1" }).textContent).toBe(
      artifact.text,
    );
    fireEvent.click(screen.getByRole("button", { name: "Retry file preparation" }));
    await screen.findByRole("button", { name: "Share shot sheet" });
    expect(mocks.generate).toHaveBeenCalledTimes(1);
    expect(mocks.prepare.mock.calls[1]![0][0].blob).toBe(artifact.blob);
    vi.mocked(prepared.share).mockResolvedValueOnce("cancelled");
    fireEvent.click(screen.getByRole("button", { name: "Share shot sheet" }));
    await screen.findByText("Sharing cancelled. Your sheet is ready to share again.");
    expect(screen.getByRole("img", { name: "Shot sheet page 1 of 1 for Station" })).toBeTruthy();
    expect(screen.getByRole("region", { name: "Text for shot sheet page 1" }).textContent).toBe(
      artifact.text,
    );
  });

  it("cancels file preparation, disposes late handles, and retries the same PNGs", async () => {
    const pending = deferred<PreparedShare>();
    const late = delivery();
    mocks.prepare.mockReturnValueOnce(pending.promise).mockResolvedValueOnce(delivery());
    setup();
    fireEvent.click(screen.getByRole("button", { name: "Preview shot sheet" }));
    await screen.findByRole("button", { name: "Cancel file preparation" });
    const signal = mocks.prepare.mock.calls[0]![1].signal as AbortSignal;
    fireEvent.click(screen.getByRole("button", { name: "Cancel file preparation" }));
    expect(signal.aborted).toBe(true);
    expect(screen.getByRole("img", { name: "Shot sheet page 1 of 1 for Station" })).toBeTruthy();
    fireEvent.click(screen.getByText("Read text for page 1"));
    expect(screen.getByRole("region", { name: "Text for shot sheet page 1" }).textContent).toBe(
      page().text,
    );
    expect(
      (screen.getByRole("button", { name: "Retry file preparation" }) as HTMLButtonElement)
        .disabled,
    ).toBe(true);
    await act(async () => pending.resolve(late));
    expect(late.dispose).toHaveBeenCalledTimes(1);
    expect(screen.queryByRole("button", { name: "Share shot sheet" })).toBeNull();
    fireEvent.click(screen.getByRole("button", { name: "Retry file preparation" }));
    await screen.findByRole("button", { name: "Share shot sheet" });
    expect(mocks.generate).toHaveBeenCalledTimes(1);
  });

  it("ignores cancelled generation and invalidates old bytes after project or shot edits", async () => {
    const old = deferred<GeneratedSheetPage[]>();
    mocks.generate.mockReturnValueOnce(old.promise).mockResolvedValue([page("new.png")]);
    const prepared = delivery();
    mocks.prepare.mockResolvedValue(prepared);
    setup();
    fireEvent.click(screen.getByRole("button", { name: "Preview shot sheet" }));
    await screen.findByRole("button", { name: "Cancel" });
    fireEvent.click(screen.getByRole("button", { name: "Cancel" }));
    expect(screen.queryByText(/Read text for page/)).toBeNull();
    fireEvent.change(screen.getByLabelText("Project title"), { target: { value: "Revised" } });
    fireEvent.change(screen.getByLabelText("Notes for Wide"), {
      target: { value: "Changed intent" },
    });
    fireEvent.click(screen.getByRole("button", { name: "Preview shot sheet" }));
    await screen.findByRole("button", { name: "Share shot sheet" });
    await act(async () => old.resolve([page("stale.png")]));
    expect(screen.getByText(/^new\.png ·/)).toBeTruthy();
    expect(screen.queryByText(/stale.png/)).toBeNull();
    fireEvent.click(screen.getByText("Read text for page 1"));
    expect(screen.getByRole("region", { name: "Text for shot sheet page 1" }).textContent).toBe(
      page("new.png").text,
    );
    expect((mocks.generate.mock.calls[1]![0] as SheetDocument).shots[0]!.notes).toBe(
      "Changed intent",
    );
    fireEvent.click(screen.getByRole("button", { name: "Edit sheet" }));
    expect(prepared.dispose).toHaveBeenCalledTimes(1);
    expect(mocks.revoke).toHaveBeenCalledWith("blob:exact-page");
    expect(screen.queryByRole("img", { name: /Shot sheet page/ })).toBeNull();
    expect(screen.queryByText(/Read text for page/)).toBeNull();
  });

  it("offers corrupt-image recovery and excludes the failed shot on retry", async () => {
    mocks.generate
      .mockRejectedValueOnce(
        new ShotSheetError("invalid-images", "Recapture or exclude the failed image.", [
          { shotId: "s1", reason: "Corrupt image" },
        ]),
      )
      .mockResolvedValue([page()]);
    setup();
    fireEvent.click(screen.getByRole("button", { name: "Preview shot sheet" }));
    await screen.findByText("Recapture or exclude the failed image.");
    expect(screen.queryByText(/Read text for page/)).toBeNull();
    expect(screen.getByRole("button", { name: "Open in scene" })).toBeTruthy();
    fireEvent.click(screen.getByRole("checkbox", { name: "Include Wide" }));
    fireEvent.click(screen.getByRole("button", { name: "Preview shot sheet" }));
    await screen.findByRole("button", { name: "Share shot sheet" });
    expect((mocks.generate.mock.calls[1]![0] as SheetDocument).shots.map(({ id }) => id)).toEqual([
      "s2",
    ]);
  });

  it("aborts on unmount and disposes a delivery handle that arrives after closing", async () => {
    const pending = deferred<PreparedShare>();
    const late = delivery();
    mocks.prepare.mockReturnValue(pending.promise);
    const view = setup();
    fireEvent.click(screen.getByRole("button", { name: "Preview shot sheet" }));
    await screen.findByRole("button", { name: "Cancel file preparation" });
    const signal = mocks.prepare.mock.calls[0]![1].signal as AbortSignal;
    view.unmount();
    expect(signal.aborted).toBe(true);
    await act(async () => pending.resolve(late));
    expect(late.dispose).toHaveBeenCalledTimes(1);
    expect(mocks.revoke).toHaveBeenCalledWith("blob:exact-page");
  });
});
